### PR TITLE
Add autotools

### PR DESCRIPTION
**Pull request by felipebalbi**
Add minimal support for autotools to facilitate maintenance

Signed-off-by: Felipe Balbi <felipe@balbi.sh>

### CODE REVIEW

**Comment by felipebalbi** [comment]
@daviwil, so this I tested against guile-2.2 which is what I had installed. If any changes are needed, let me know and I can work on them ;-) Hopefully this works find on guix too.

**Comment by felipebalbi** [comment]
Updated based on latest push

**Comment by felipebalbi** [comment]
We may have to relax autoconf prereq to 2.69 if you want to run CI on github (got a setup for that too if you want)

**Comment by daviwil** [comment]
Thanks a lot for sending this!  I've never used `autotools` before so it's interesting to see how it would be applied here.  To be honest, I'm considering switching to using Zig for builds (and possibly for the native side) so I'll hold off on merging this until I've made a decision on that.

**Comment by felipebalbi** [comment]
No worries @daviwil. Cheers, happy new year

**Comment by daviwil** [comment]
Happy New Year to you as well!

**Comment by daviwil** [comment]
Thanks again for sending this!  PR #8 converted the project build to CMake which turned out to be very helpful in getting `lsp-mode` to work for the C code.  Looks like we're now back to your original suggestion :)

**Pull request closed without merging**
