### PR TITLE
Correct issues with stack smashing

### LINKED ISSUE #10: Stack smashing detected
Whenever we compile with a GCC that enables stack protection by default, we get into stack protection issues, presumably due to the fact that flux-compose:

1. Uses stack-allocated memory for virtually everything; and
2. Virtually every struct has a VLA at the end for the name string

Combined, these two result in the following:

```
./run-tests

Flux Compose Test Runner


 • SUITE test_vector_suite
  ✓ PASS test_vector_empty
  ✓ PASS test_vector_push
*** stack smashing detected ***: terminated
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by felipebalbi**
Fixes #10

### CODE REVIEW

**Comment by daviwil** [comment]
Ouch, yeah, I hadn't considered that aspect when I started using stack-allocated structs for initialization.  Maybe I should go back to using pointers to initialize memory locations inside of the allocated vector memory?  I started using the stack allocation approach because it simplified the vector API a bit, but it seems that has its own problems.

**Comment by felipebalbi** [comment]
Yeah, ideally you'd own all the memory you're using explicitly. I'd do my best to skip VLAs if possible, though.

**Comment by daviwil** [comment]
Is there a better pattern for storing strings only at the size needed for the characters involved?  I'd rather not have to specify a size up front if it's just going to be dead space in many cases.  Maybe a separate string table (big preallocated char array) where I stash strings and then the other struct keeps a pointer to the string location in that array?

**Comment by felipebalbi** [comment]
> Is there a better pattern for storing strings only at the size needed for the characters involved?

Perhaps keeping a pointer to the string in your token type strings. Then to initialize it, compute the size of the string in question and malloc() enough memory for it.

> I'd rather not have to specify a size up front if it's just going to be dead space in many cases.

understandable, this was just the simplest, quickest solution to the problem until a better idea shows up. Minimal impact :-)

> Maybe a separate string table (big preallocated char array) where I stash strings and then the
> other struct keeps a pointer to the string location in that array?

I'd avoid that too as there would always be a possibility of overflowing that as well.

**Comment by daviwil** [comment]
> Perhaps keeping a pointer to the string in your token type strings. Then to initialize it, compute the size of the string in question and malloc() enough memory for it.

Yeah, I was trying to avoid stray `malloc`s so that I can keep the expression data co-located in memory as much as possible, but maybe that is infeasible after all.  I suppose what I'm learning here is that cache-friendly code is most applicable when dealing with homogeneous data types.

> understandable, this was just the simplest, quickest solution to the problem until a better idea shows up. Minimal impact :-)

Definitely appreciate the intention!  Incremental progress is always best.

**Comment by felipebalbi** [comment]
> > Perhaps keeping a pointer to the string in your token type strings. Then to initialize it, compute the size of the string in question and malloc() enough memory for it.
> 
> Yeah, I was trying to avoid stray `malloc`s so that I can keep the expression data co-located in memory as much as possible, but maybe that is infeasible after all. I suppose what I'm learning here is that cache-friendly code is most applicable when dealing with homogeneous data types.

Perhaps deal with cache friendliness once it becomes an issue? Then again, this is only for the tokenizer and parser which are used only once per run, at least so far. Not much of an issue, I guess.

Maybe in the future, we could run `flux-compose` through `perf` to get some tangible data on bottlenecks on the application ;-)

**Comment by daviwil** [comment]
Yep, cache optimization isn't really needed at this point.  I was a little too excited to play with manual memory management :)

**Comment by daviwil** [comment]
By the way, thanks for adding `SKIP` to the test library!  I'll merge this now.

**Comment by felipebalbi** [comment]
> By the way, thanks for adding `SKIP` to the test library! I'll merge this now.

No worries, happy to help :-)

BTW, I was looking at the tokenizer and the calls to `strcpy()`, it seems like we're always copying from the beginning of `str_buffer`. Shouldn't we copy from `str_buffer[str_ptr]` instead? If you want, I can file a dedicated issue to discuss

**Comment by daviwil** [comment]
After I copy the string to finish a token, I call `token_reset_state` which resets `str_ptr` back to `&str_buffer[0]` so the next string will always start at the zeroth index.  Definitely happy to discuss if there's a better (or safer) way to do that.  I need to improve my C coding practices!

**Pull request merged**
